AWSTemplateFormatVersion: "2010-09-09"
Description: (SO0042-statemachine) Media Analysis Solution - The AWS CloudFormation template that provisions the Media Analysis Solution state machine using Amazon Step Functions.

Parameters:
  MediaAnalysisPreprocessFunction:
      Type: String
      Description: "ARN of the Media Analysis Lambda function"
  StateMachineName:
      Type: String
      Description: "Name of the Media Analysis state machine"

Resources:
  MediaAnalysisPreprocessStateMachine:
      Type: AWS::StepFunctions::StateMachine
      Properties:
          StateMachineName: !Ref StateMachineName
          DefinitionString:
            !Sub
              - |-
                {
                "StartAt": "Preprocess Media",
                "States": {
                  "Preprocess Media": {
                    "Type": "Parallel",
                    "Next": "Complete Stage",
                    "ResultPath": "$.stage",
                    "Branches": [{
                      "StartAt": "Stage Name",
                      "States": {
                        "Stage Name": {
                        "Type": "Pass",
                        "Result": {
                          "stage": "preprocess"
                        },
                        "ResultPath": "$.stage",
                        "Next": "Convert to Audio"
                      },
                      "Convert to Audio": {
                        "Type": "Pass",
                        "Result": {
                          "service_name": "media_convert",
                          "function_name": "start_media_convert"
                        },
                        "ResultPath": "$.lambda",
                        "Next": "Start MediaConvert"
                      },
                      "Start MediaConvert": {
                        "Type": "Task",
                        "Resource": "${lambdaArn}",
                        "InputPath": "$",
                        "ResultPath": "$.mediaConvert",
                        "Next": "Did MediaConvert Start"
                      },
                      "Did MediaConvert Start": {
                        "Type": "Choice",
                        "Choices": [{
                          "Variable": "$.mediaConvert.jobDidStart",
                          "BooleanEquals": true,
                          "Next": "MediaConvert Wait"
                        }],
                        "Default": "Job Failed"
                      },
                      "MediaConvert Wait": {
                        "Type": "Wait",
                        "Seconds": 30,
                        "Next": "Get MediaConvert Status Params"
                      },
                      "Get MediaConvert Status Params": {
                        "Type": "Pass",
                        "Result": {
                          "service_name": "media_convert",
                          "function_name": "get_status"
                        },
                        "ResultPath": "$.lambda",
                        "Next": "Get MediaConvert Status"
                      },
                      "Get MediaConvert Status": {
                        "Type": "Task",
                        "Resource": "${lambdaArn}",
                        "InputPath": "$",
                        "ResultPath": "$",
                        "Next": "Did MediaConvert Complete"
                      },
                      "Did MediaConvert Complete": {
                        "Type": "Choice",
                        "Choices": [
                          {
                            "Variable": "$.mediaConvert.status",
                            "StringEquals": "FAILED",
                            "Next": "Job Failed"
                          },
                          {
                            "Variable": "$.mediaConvert.status",
                            "StringEquals": "COMPLETE",
                            "Next": "Job Succeeded"
                          }
                        ],
                        "Default": "MediaConvert Wait"
                      },
                      "Job Failed": {
                        "Type": "Fail"
                      },
                      "Job Succeeded": {
                        "Type": "Pass",
                        "Result": {
                          "status": "complete"
                        },
                        "ResultPath": "$.stageStatus",
                        "Next": "Update Key"
                      },
                      "Update Key": {
                        "Type": "Pass",
                        "InputPath": "$.key", 
                        "ResultPath": "$.outputs.key",
                        "Next": "Update Destination"
                      },
                      "Update Destination": {
                        "Type": "Pass",
                        "InputPath": "$.mediaConvert.data.Job.Settings.OutputGroups[0].OutputGroupSettings.FileGroupSettings.Destination", 
                        "ResultPath": "$.outputs.destination",
                        "Next": "Update File Type"
                      },
                      "Update File Type": {
                        "Type": "Pass",
                        "InputPath": "$.mediaConvert.data.Job.Settings.OutputGroups[0].Outputs[0].Extension", 
                        "ResultPath": "$.outputs.file_type",
                        "Next": "Update Outputs"
                      },
                      "Update Outputs": {
                        "Type": "Pass",
                        "InputPath": "$.stage[0]",
                        "ResultPath": "$.outputs",
                        "End": true
                      }
                      }
                    }]
                  },
                  "Complete Stage": {
                    "Type": "Pass",
                    "End": true
                  }        
                }
                }
              - {lambdaArn: !Ref MediaAnalysisPreprocessFunction}
          RoleArn: !GetAtt MediaAnalysisPreprocessStateMachineRole.Arn

  MediaAnalysisPreprocessStateMachineRole:
      Type: AWS::IAM::Role
      Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Principal:
                  Service:
                    - !Join ["", ["states.", Ref: "AWS::Region", ".amazonaws.com"]]
                Action:
                  - "sts:AssumeRole"
          Path: /
          Policies:
            -
              PolicyName: media-analysis-preprocess-state-machine-policy
              PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                    -
                      Effect: "Allow"
                      Action:
                        - "lambda:InvokeFunction"
                      Resource: !Ref MediaAnalysisPreprocessFunction

Outputs:
  MediaAnalysisPreprocessStateMachineArn:
    Description: PreprocessStateMachine
    Value: !Ref MediaAnalysisPreprocessStateMachine
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MediaAnalysisPreprocessStateMachineArn ] ]
  MediaAnalysisPreprocessStateMachineRoleArn:
    Description: Stage definition table
    Value: !Ref MediaAnalysisPreprocessStateMachineRole
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", MediaAnalysisPreprocessStateMachineRoleArn ] ]